import 'package:p/Features/solar_system/presentation/view_models/planets_info_model.dart';

class GetPlanets {
  static List<PlanetsInfoModel> planetsModel = [
    PlanetsInfoModel(
      title: 'Mercury',
      subTitle: 'Mercury Description',
      image: 'images/Mercury.png',
      description:
          'Mercury is the smallest and innermost planet, with a rocky, cratered surface that resembles Earth\'s Moon. Its surface temperatures can swing drastically from extremely hot to freezing cold due to its lack of a significant atmosphere.',
      distance:
          'Mercury is approximately 77 million kilometers (48 million miles) from Earth at its closest approach.',
      moons: 'None.',
      rings: 'None.',
      atmosphere:
          'Mercury has a very thin atmosphere composed mostly of oxygen, sodium, hydrogen, helium, and potassium.',
      surfaceFeatures:
          'Mercury\'s surface is marked by vast plains, steep cliffs (scarps), and the Caloris Basin—a massive impact crater over 1,500 kilometers (930 miles) in diameter.',
      exploration:
          'NASA\'s Mariner 10 and MESSENGER missions have provided most of what we know about Mercury. The BepiColombo mission is currently en route to study the planet further.',
      potentialForLife:
          'Mercury\'s extreme temperatures and lack of a stable atmosphere make it highly unlikely to support life as we know it.',
      funFacts:
          'Mercury\'s orbit is the most eccentric (elliptical) of all the planets, leading to significant variations in its distance from the Sun.',
      model3D: 'images/Mercury_1_4878.glb',
    ),
    PlanetsInfoModel(
      title: 'Venus',
      subTitle: 'Venus Description',
      image: 'images/Venus.png',
      description:
          'Venus, Earth\'s "sister planet," is similar in size and structure but vastly different in climate. It\'s enveloped in thick clouds of sulfuric acid, creating a runaway greenhouse effect that makes it the hottest planet in the Solar System.',
      distance:
          'Venus is about 41 million kilometers (25 million miles) away at its closest approach, making it Earth\'s closest planetary neighbor.',
      moons: 'None.',
      rings: 'None.',
      atmosphere:
          'Venus has a dense atmosphere composed mainly of carbon dioxide, with clouds of sulfuric acid and traces of water vapor.',
      surfaceFeatures:
          'The surface of Venus is relatively young and features vast volcanic plains, large shield volcanoes, and highland regions like Ishtar Terra and Aphrodite Terra.',
      exploration:
          'Venus has been extensively studied by spacecraft, including the Soviet Venera missions and NASA’s Magellan orbiter.',
      potentialForLife:
          'The surface of Venus is inhospitable, but speculation exists about microbial life in the cooler, upper layers of its atmosphere.',
      funFacts:
          'Venus\'s surface temperature is hot enough to melt lead, reaching up to 475°C (900°F).',
      model3D: 'images/venus.glb',
    ),
    PlanetsInfoModel(
      title: 'Earth',
      subTitle: 'Earth Description',
      image: 'images/img_earth.png',
      description:
          'Earth is the only planet known to harbor life, thanks to its liquid water, atmosphere rich in oxygen, and suitable temperature range.',
      distance:
          'Earth is about 150 million kilometers (93 million miles) from the Sun, placing it within the "Goldilocks zone" where conditions are just right for liquid water to exist.',
      moons: 'One (the Moon).',
      rings: 'None.',
      atmosphere:
          'Earth\'s atmosphere is composed mainly of nitrogen (78%) and oxygen (21%), with traces of other gases like argon and carbon dioxide.',
      surfaceFeatures:
          'Earth’s surface is 71% water, with landmasses divided into continents. It has a variety of features, including mountains, valleys, plains, and volcanic activity.',
      exploration:
          'Human exploration of Earth is unparalleled, with continuous advancements in technology allowing us to study the planet from its core to the outer atmosphere.',
      potentialForLife:
          'Earth is teeming with life in diverse forms, from microorganisms to complex plants and animals, in nearly every environment.',
      funFacts:
          'Earth’s magnetic field, generated by its molten iron core, protects us from harmful solar wind and cosmic radiation.',
      model3D: 'images/earth.glb',
    ),
    PlanetsInfoModel(
      title: 'Mars',
      subTitle: 'Mars Description',
      image: 'images/img_mars.png',
      description:
          'Mars is a cold desert world with a thin atmosphere. It has a history of liquid water and is often a focus in the search for past life.',
      distance:
          'Mars is about 225 million kilometers (140 million miles) from Earth on average.',
      moons: 'Two (Phobos and Deimos).',
      rings: 'None.',
      atmosphere:
          'Mars has a thin atmosphere composed mostly of carbon dioxide (95%), with traces of nitrogen and argon.',
      surfaceFeatures:
          'Mars has the tallest volcano (Olympus Mons) and deepest canyon (Valles Marineris) in the Solar System.',
      exploration:
          'NASA’s Curiosity and Perseverance rovers have been exploring the planet for signs of past life.',
      potentialForLife:
          'Conditions on ancient Mars could have supported microbial life. Ongoing missions are searching for evidence.',
      funFacts:
          'Mars has seasons similar to Earth’s and signs of ancient river valleys and lake beds.',
      model3D: 'images/mars.glb',
    ),
    PlanetsInfoModel(
      title: 'Jupiter',
      subTitle: 'Jupiter Description',
      image: 'images/Jupiter.png',
      description:
          'Jupiter is the largest planet in the Solar System, known for its Great Red Spot, a storm that has raged for centuries.',
      distance:
          'Jupiter is about 628 million kilometers (390 million miles) from Earth on average.',
      moons:
          '95 confirmed moons, including the Galilean moons Io, Europa, Ganymede, and Callisto.',
      rings: 'Yes, though faint and made of dust.',
      atmosphere:
          'Jupiter\'s atmosphere is mostly hydrogen and helium, with intense storms and complex cloud patterns.',
      surfaceFeatures:
          'Jupiter has no solid surface, with a gaseous and liquid composition.',
      exploration:
          'NASA’s Juno mission is providing detailed information about Jupiter’s atmosphere and magnetic field.',
      potentialForLife:
          'Jupiter is inhospitable, but some of its moons, like Europa, may have conditions suitable for life.',
      funFacts:
          'Jupiter is so massive that it has more than twice the mass of all other planets combined.',
      model3D: 'images/jupiter.glb',
    ),
    PlanetsInfoModel(
      title: 'Saturn',
      subTitle: 'Saturn Description',
      image: 'images/Saturn.png',
      description:
          'Saturn is the second-largest planet, known for its stunning and complex ring system made mostly of ice particles.',
      distance:
          'Saturn is about 1.2 billion kilometers (746 million miles) from Earth.',
      moons:
          '145 confirmed moons, with Titan being the largest and most intriguing.',
      rings:
          'Yes, Saturn\'s rings are the most extensive and complex in the Solar System.',
      atmosphere:
          'Saturn\'s atmosphere is mostly hydrogen and helium, with periodic large storms called "Great White Spots".',
      surfaceFeatures:
          'Saturn has no solid surface, with gas and liquid layers and a possible rocky core.',
      exploration:
          'NASA’s Cassini mission provided an in-depth study of Saturn, its rings, and moons.',
      potentialForLife:
          'Saturn itself is inhospitable, but its moons Titan and Enceladus may harbor life.',
      funFacts:
          'Saturn would float in water if such a large body of water existed.',
      model3D: 'images/saturn.glb',
    ),
    PlanetsInfoModel(
      title: 'Uranus',
      subTitle: 'Uranus Description',
      image: 'images/URANUS.png',
      description:
          'Uranus is an ice giant, known for its bluish-green color due to methane in its atmosphere and its extreme axial tilt.',
      distance:
          'Uranus is about 2.6 billion kilometers (1.6 billion miles) away on average.',
      moons: '27 known moons, with Titania being the largest.',
      rings: 'Yes, Uranus has faint rings made mostly of dark particles.',
      atmosphere:
          'Uranus\'s atmosphere is mostly hydrogen, helium, and methane.',
      surfaceFeatures:
          'Uranus has no solid surface, and its tilted axis results in extreme seasonal variations.',
      exploration:
          'Voyager 2 is the only spacecraft to have visited Uranus, in 1986.',
      potentialForLife:
          'Uranus’s harsh conditions make it unlikely to support life.',
      funFacts:
          'A day on Uranus takes about 17 hours, but one pole can be in darkness or daylight for 42 years.',
      model3D: 'images/uranus.glb',
    ),
    PlanetsInfoModel(
      title: 'Neptune',
      subTitle: 'Neptune Description',
      image: 'images/NEPTUNE.png',
      description:
          'Neptune, the farthest planet from the Sun, is an ice giant known for its strong winds and dark storm systems.',
      distance:
          'Neptune is about 4.3 billion kilometers (2.7 billion miles) away from Earth.',
      moons: '14 known moons, with Triton being the largest.',
      rings: 'Yes, Neptune has faint rings, with some denser segments.',
      atmosphere:
          'Neptune’s atmosphere is mostly hydrogen, helium, and methane, with the fastest winds in the Solar System.',
      surfaceFeatures:
          'Neptune has no solid surface and active weather patterns, including large dark storms.',
      exploration:
          'Voyager 2 passed by Neptune in 1989, providing detailed images and data.',
      potentialForLife:
          'Neptune is inhospitable, but Triton, with its active geysers, is a point of interest.',
      funFacts:
          'Despite its distance from the Sun, Neptune radiates more heat than it receives.',
      model3D: 'images/neptune.glb',
    ),
  ];
}
