class PlanetsInfoModel {
  final String title;
  final String description;
  final String distance;
  final String moons;
  final String rings;
  final String atmosphere;
  final String surfaceFeatures;
  final String exploration;
  final String potentialForLife;
  final String funFacts;

  PlanetsInfoModel(
      {required this.title,
      required this.description,
      required this.distance,
      required this.moons,
      required this.rings,
      required this.atmosphere,
      required this.surfaceFeatures,
      required this.exploration,
      required this.potentialForLife,
      required this.funFacts});

  factory PlanetsInfoModel.fromJson(json) {
    return PlanetsInfoModel(
      title: json['title'],
      description: json['Description'],
      distance: json['Distance'],
      moons: json['Moons'],
      rings: json['Rings'],
      atmosphere: json['Atmosphere'],
      surfaceFeatures: json['Surface'],
      exploration: json['Exploration'],
      potentialForLife: json['Potential'],
      funFacts: json['Fun Facts'],
    );
  }

//       final List<PlanetsModel> planetsModel = [
//   PlanetsModel(
//     title: 'Earth',
//     subTitle: 'Earth Description',
//     image: 'images/img_earth.png',
//     description:
//         'Earth is the only planet known to harbor life, thanks to its liquid water, atmosphere rich in oxygen, and suitable temperature range. It\'s a dynamic planet with constantly shifting tectonic plates, diverse ecosystems, and a unique climate system.',
//     distance:
//         'Earth is about 150 million kilometers (93 million miles) from the Sun, placing it within the "Goldilocks zone" where conditions are just right for liquid water to exist.',
//     moons: 'One (the Moon).',
//     rings: 'None.',
//     atmosphere:
//         'Earth\'s atmosphere is composed mainly of nitrogen (78%) and oxygen (21%), with traces of other gases like argon and carbon dioxide. It protects life from harmful solar radiation and helps regulate the planet\'s temperature.',
//     surfaceFeatures:
//         'Earth’s surface is 71% water, with landmasses divided into continents. It has a variety of features, including mountains, valleys, plains, and volcanic activity.',
//     exploration:
//         'Human exploration of Earth is unparalleled, with continuous advancements in technology allowing us to study the planet from its core to the outer atmosphere. Space missions have also provided unique perspectives on Earth.',
//     potentialForLife:
//         'Earth is teeming with life in diverse forms, from microorganisms to complex plants and animals, in nearly every environment.',
//     funFacts:
//         'Earth’s magnetic field, generated by its molten iron core, protects us from harmful solar wind and cosmic radiation.',
//   ),
//   PlanetsModel(
//     title: 'Mars',
//     subTitle: 'Mars Description',
//     image: 'images/img_mars.png',
//     description:
//         'Earth is the only planet known to harbor life, thanks to its liquid water, atmosphere rich in oxygen, and suitable temperature range. It\'s a dynamic planet with constantly shifting tectonic plates, diverse ecosystems, and a unique climate system.',
//     distance:
//         'Earth is about 150 million kilometers (93 million miles) from the Sun, placing it within the "Goldilocks zone" where conditions are just right for liquid water to exist.',
//     moons: 'One (the Moon).',
//     rings: 'None.',
//     atmosphere:
//         'Earth\'s atmosphere is composed mainly of nitrogen (78%) and oxygen (21%), with traces of other gases like argon and carbon dioxide. It protects life from harmful solar radiation and helps regulate the planet\'s temperature.',
//     surfaceFeatures:
//         'Earth’s surface is 71% water, with landmasses divided into continents. It has a variety of features, including mountains, valleys, plains, and volcanic activity.',
//     exploration:
//         'Human exploration of Earth is unparalleled, with continuous advancements in technology allowing us to study the planet from its core to the outer atmosphere. Space missions have also provided unique perspectives on Earth.',
//     potentialForLife:
//         'Earth is teeming with life in diverse forms, from microorganisms to complex plants and animals, in nearly every environment.',
//     funFacts:
//         'Earth’s magnetic field, generated by its molten iron core, protects us from harmful solar wind and cosmic radiation.',
//   ),
// ];
}
