// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWL-rl9JnhlJjYVQud_u18Nxcs1nSyaeY',
    appId: '1:575485087222:web:e1f3b3933cf7286eeccbd7',
    messagingSenderId: '575485087222',
    projectId: 'nasa-space-app-f9acb',
    authDomain: 'nasa-space-app-f9acb.firebaseapp.com',
    storageBucket: 'nasa-space-app-f9acb.appspot.com',
    measurementId: 'G-LNEW6HH6J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0hb164J5aDm37MgvUEZl2YiFKcaMqdQ',
    appId: '1:575485087222:android:9b396afa6e480d1aeccbd7',
    messagingSenderId: '575485087222',
    projectId: 'nasa-space-app-f9acb',
    storageBucket: 'nasa-space-app-f9acb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd7Vo0fDAMa8gOpSc67w3fWpL67IrESM',
    appId: '1:575485087222:ios:f08a637dc267413beccbd7',
    messagingSenderId: '575485087222',
    projectId: 'nasa-space-app-f9acb',
    storageBucket: 'nasa-space-app-f9acb.appspot.com',
    iosBundleId: 'com.example.nasaSpaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGd7Vo0fDAMa8gOpSc67w3fWpL67IrESM',
    appId: '1:575485087222:ios:f08a637dc267413beccbd7',
    messagingSenderId: '575485087222',
    projectId: 'nasa-space-app-f9acb',
    storageBucket: 'nasa-space-app-f9acb.appspot.com',
    iosBundleId: 'com.example.nasaSpaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWL-rl9JnhlJjYVQud_u18Nxcs1nSyaeY',
    appId: '1:575485087222:web:faca69863ed0f479eccbd7',
    messagingSenderId: '575485087222',
    projectId: 'nasa-space-app-f9acb',
    authDomain: 'nasa-space-app-f9acb.firebaseapp.com',
    storageBucket: 'nasa-space-app-f9acb.appspot.com',
    measurementId: 'G-03R09BK4JH',
  );
}
